apiVersion: v1
kind: Service
metadata:
    name: web
    labels:
      name: web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: web
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: web-controller
spec:
  replicas: 2
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: jmcminingappchapter28d37.azurecr.io/jmc-mining-app:v1
        name: web
        ports:
        - containerPort: 3000
          name: http-server
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m